#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "reader.h"
#include "vm.h"

extern Obj reverse(struct VM *vm, int pos, int O);

void readFileAsSexp(void *pc, Obj val, struct VM *vm, int pos) {
  Obj path = vmGet(vm, 1);
  Obj pkg = vmGet(vm, 2);

  struct SexpReader r = {.pkgMapping = Nil, .selfPath = toCStr(stringStr(pkg))};
  strBuf pathStr = stringStr(path);
  FILE* f = fopen(toCStr(pathStr), "r");
  int errCode = 0;

  int ret = pos++;
  vmSet(vm, ret, Nil);
  int v = pos++;
  while(errCode == 0) {
    vmSet(vm, v, sexpRead(vm, pos, &r, f, &errCode));
    vmSet(vm, ret, vmCons(vm, v, ret));
  }
  fclose(f);

  Obj tmp = reverse(vm, pos, ret);
  vmReturn(vm, tmp);
}

void writeSexpToFile(void *pc, Obj val, struct VM *vm, int pos) {
  Obj path = vmGet(vm, 1);
  Obj exp = vmGet(vm, 2);
  strBuf pathStr = stringStr(path);
  FILE* f = fopen(toCStr(pathStr), "w");
  /* printObj(stdout, exp); */
  printObj(f, exp);
  fclose(f);
  vmReturn(vm, Nil);
}

int main(int argc, char *argv[]) {
  struct VM *vm = newVM();
  int pos = 0;
  loadByteCode(vm, pos, cstr("../init.bc"));
  loadByteCode(vm, pos, cstr("../compile.bc"));

  symbolSet(makeSymbol("read-file-as-sexp"), makePrimitive(readFileAsSexp, 2));
  symbolSet(makeSymbol("write-sexp-to-file"), makePrimitive(writeSexpToFile, 2));

  // (load "lib/bootstrap.cora" "")  to generate the new init.bc and compile.bc
  char *s = "../lib/bootstrap.cora";
  int tmp = pos++;
  vmSet(vm, tmp, cons(intern("load"), cons(makeString(s, strlen(s)), cons(makeString("", 0), Nil))));
  eval(vm, pos, tmp);

  // Check the new generated bytecode can be load successfully
  loadByteCode(vm, pos, cstr("./init.bc"));
  loadByteCode(vm, pos, cstr("./compile.bc"));
}
