#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "reader.h"
#include "vm.h"

extern Obj reverse(struct VM *vm, int pos, Obj o);


int main(int argc, char *argv[]) {
  struct VM *vm = newVM();
  loadByteCode(vm, cstr("../init.bc"));
  loadByteCode(vm, cstr("../compile.bc"));

  // (load "lib/bootstrap.cora" "")  to generate the new init.bc and compile.bc
  char *s = "../lib/bootstrap.cora";
  eval(vm, cons(NULL, 0, intern("load"), cons(NULL, 0, makeString(NULL, 0, s, strlen(s)), cons(NULL, 0, makeString(NULL, 0, "", 0), Nil))));

  // Check the new generated bytecode can be load successfully
  loadByteCode(vm, cstr("./init.bc"));
  loadByteCode(vm, cstr("./compile.bc"));
}
